version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "81:80"
      - "443:443"
    environment:
      - BACKEND_DIR=${BACKEND_DIR}
    volumes:
      - ./frontend/index:/usr/share/nginx/html
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://miusuario:mipassword@database:5432/mibasededatos
    depends_on:
      - database
    restart: unless-stopped

  database:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: miusuario
      POSTGRES_PASSWORD: mipassword
      POSTGRES_DB: mibasededatos
    volumes:
      - ./DBdata:/var/lib/postgresql/data
    restart: unless-stopped
  
volumes:
  postgres_data:
